name: "Ai Review DHG"
description: "Git action AI review"
author: "dhgvieira"

inputs:
  secret_github:
    description: git token default
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    #
    - name: Install dependencies
      run: pip install -r ${{ github.action_path }}/src/requirements.txt
      shell: bash

    - name: Install git
      run: apt get install git
      shell: bash

    - name: Run Reviewer Script
      env:
        GITHUB_HEAD_REF: ${{ github.head_ref }}
        GITHUB_BASE_REF: ${{ github.base_ref }}
        CHATGPT_KEY: 12312312321
        CHATGPT_MODEL: gpt-3.5-turbo
        GITHUB_TOKEN: ${{ inputs.secret_github }}
        TARGET_EXTENSIONS: java
        REPO_OWNER: ${{ github.repository_owner }}
        REPO_NAME: ${{ github.event.repository.name }}
        PULL_NUMBER: ${{ github.event.number }}
      run: |
        python ${{ github.action_path }}/src/github_reviewer.py
      shell: bash
